### ISSUE TITLE
do i need yolo?

### ISSUE THREAD

**Issue by ozett** [thebigpotatoe/Node-Red-Yolo-Pets-And-People#1]
i try to give your node-flow a  shot.
the readme.md states that

> The Yolo Folder option is required

as i cloned the repo i have the subdir, but there is no yolo inside. isnt it?
do i have to download it separately? where to put?

if start the yolo.py in the clones subdir, i got missing depencies.
how should i solve it?

```
olaf@node3:~/nr-yolopets/yolodata$ python3 --version
Python 3.6.9
olaf@node3:~/nr-yolopets/yolodata$ python3 yolo.py
Traceback (most recent call last):
  File "yolo.py", line 2, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
olaf@node3:~/nr-yolopets/yolodata$

```

what about using a virtualenvironment?
(may use this: https://flows.nodered.org/flow/778859ca2503db35ff0e12341508efef )

**Comment by thebigpotatoe** [comment]
Hey mate,

I should start by saying this is rather old work for me, and I have had a fair bit more experience in Python since building this. So most of the stuff in this repo will be out of date or designed poorly, and as such I'm not looking at maintaining it. But to answer your questions;

> > The Yolo Folder option is required
> as i cloned the repo i have the subdir, but there is no yolo inside. isnt it?
> do i have to download it separately? where to put?

The folder must come with the repo, that's part of cloning. However what I realise now is that without git LFS you will not download the weights. You will need to download them from [here](https://pjreddie.com/media/files/yolov3.weights) and save them into your cloned folder in the Yolo directory. Just make sure you navigate to the correct location where you downloaded it.

> if start the yolo.py in the clones subdir, i got missing depencies.
> how should i solve it?

This is poor design on my behalf. It expects these dependencies in your system wide python install. While you can run the script this way after installing the `requirements.txt` in this repo, its not a great way of running the script in general.

As you state you can (and should) run it using a virtual env. That node linked looks great, but I have no idea how to use it. So my suggestion would be to fork this repo, and figure out if you can run the script with that node for your deployment.

**Comment by ozett** [comment]
i  work out your hints and report later
thanks

**Comment by ozett** [comment]
so far, so good. i will use your flow as an example to learn something,
now i am stuck with a missing depency, wich is installed:

![image](https://user-images.githubusercontent.com/5937811/82673837-b3690400-9c42-11ea-9945-4fd27793275c.png)

do you have a clue, how i check under which user my node-red/python.cmd is running?
i installed node-red with the raspi-script and it is running under the user "olaf".
on the command-line the depency is fullfilled,
but if i trigger it from node-red with your subflow, there is an error in the debug.
it is also installed as root. so i dont know where to search now...

some hints? greatly appreciate it. 😄

**Comment by ozett** [comment]
got it running!

![image](https://user-images.githubusercontent.com/5937811/82675495-312e0f00-9c45-11ea-982e-61a1fe13c3ae.png)

**Comment by ozett** [comment]
i changed the subflow command from "python" to "python3"
![image](https://user-images.githubusercontent.com/5937811/82675603-5a4e9f80-9c45-11ea-9888-9deaf113322e.png)

**Comment by ozett** [comment]
and i installed cv2 as my node-red useraccount "olaf" within usershell and:

`pip install opencv-contrib-python`

after the install-documentation from pyimagesearch:
![image](https://user-images.githubusercontent.com/5937811/82675720-82d69980-9c45-11ea-89b2-d9972169520b.png)

**Comment by ozett** [comment]
💐

**Comment by thebigpotatoe** [comment]
What a roller coaster haha. Glad it's working and you had fun. 

I'm going to close this issue since it seems to be fixed.

**Comment by ozett** [comment]
just for the record: virtualenv could be done  with the pythonshell.in node
(wich i found just a minute ago by accident)

![image](https://user-images.githubusercontent.com/5937811/82755926-1f7c7100-9dd7-11ea-9539-a080e8d9742b.png)

**Comment by thebigpotatoe** [comment]
Nice, this could be really useful for this node and future ones. Thanks for the heads up.

**Comment by ozett** [comment]
i now tried to implement your flow on a jetson nano.

but after some tweaks i found no darknet/yolo on the whole system.

i am wondering now what has made things happen on my first x86 system.
as far as i looked up the web i must compile yolo to use it as an opencv-dnn.

why didnt i had to do this first time? i can only remember cloning your repo and got it running...

**Comment by ozett** [comment]
i consider going to install yolov4 to see if i can get it running specialy on the jetson nano ...
https://jkjung-avt.github.io/yolov4/

**Comment by ozett** [comment]
what did i found?

yolo v3 is build into opencv as dnn on most versions. also into opencv v4.1.1 
seems so on my nano from the nvidia repo (i guess).

yolo v4 has succesful build on my nano. but no or a hard way to integrate that build into opencv.

i can run darknet inference stand-alone (=yolo v4).

the opencv-integration of yolo v4 can be managed by own compile of opencv or waiting for an new release with integrated dnn , see status here: https://github.com/AlexeyAB/darknet/issues/5671

**Comment by ozett** [comment]
maybe a way to get yolo v4 into opencv ...

https://github.com/jkjung-avt/tensorrt_demos#demo-5-yolov4
